steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/three-tier-app-fe:$_IMAGE_TAG', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/three-tier-app-fe:$_IMAGE_TAG']
substitutions:
  _IMAGE_TAG: latest
