services:
  db:
    image: postgres:16.3-bullseye
    container_name: todo-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_user_root
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: "npm run dev"
    volumes:
      - ./frontend:/app:cached
    ports:
      - "8080:8080"
volumes:
  postgres_data: {}
networks:
  default:
    name: todo_network
